### ISSUE TITLE
Content are not centered in Chrome browser

### ISSUE THREAD

**Issue by zulhfreelancer** [KatsuteDev/GitHub-Center#9]
### Operating System

Mac OS 14.5

### Browser

Chrome 125.0.6422.113

### Extension Version

1.1

### Issue

Just want to report a bug here.

Sample page:

https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-configuration-files.md

Screenshot:

![image](https://github.com/KatsuteDev/GitHub-Center/assets/3416976/4374960b-d849-4e26-8517-d06789a3250a)

Can we move the yellow boxes into the red box? In other words, I would expect the content to be centered too i.e. everything is placed inside the red box; blue boxes to show yellow boxes contents.

Site navigation (green box) looks OK and should be left untouched.

**Comment by Katsute** [comment]
I think it would be better 
![image](https://github.com/KatsuteDev/GitHub-Center/assets/58778985/fa61d12c-7159-4e1b-bbbd-06ae194bd1b6)

**Comment by zulhfreelancer** [comment]
Most of the time, I will close/hide the right sidebar and I prefer that way.

Can we have an option page to toggle this?

**Comment by Katsute** [comment]
Possibly, I'll look into it

**Comment by zulhfreelancer** [comment]
Thank you!
